### ISSUE TITLE
-Dtests=true fails to build on BSDs due to -I= instead of -I or -isystem

### ISSUE THREAD

**Issue by jbeich** [any1/neatvnc#66]
Regressed by d0cf1595af15. Doesn't affect `-Dtests=false` (default) builds.

```c
$ meson setup -Dtests=true /tmp/neatvnc_build
$ meson compile -C /tmp/neatvnc_build
[...]
FAILED: test/pixels.p/test-pixels.c.o
cc -Itest/pixels.p -Itest -Itest -Iinclude -I/usr/local/include/pixman-1 -I=/usr/local/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu11 -O0 -g '-DPROJECT_VERSION="0.5.0"' -D_GNU_SOURCE -fvisibility=hidden -Wmissing-prototypes '-DGIT_VERSION="v0.5.0-1-gcd23192 (freebsd)"' -MD -MQ test/pixels.p/test-pixels.c.o -MF test/pixels.p/test-pixels.c.o.d -o test/pixels.p/test-pixels.c.o -c test/test-pixels.c
test/test-pixels.c:8:10: fatal error: 'libdrm/drm_fourcc.h' file not found
#include <libdrm/drm_fourcc.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: test/pixels.p/.._src_pixels.c.o
cc -Itest/pixels.p -Itest -Itest -Iinclude -I/usr/local/include/pixman-1 -I=/usr/local/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu11 -O0 -g '-DPROJECT_VERSION="0.5.0"' -D_GNU_SOURCE -fvisibility=hidden -Wmissing-prototypes '-DGIT_VERSION="v0.5.0-1-gcd23192 (freebsd)"' -MD -MQ test/pixels.p/.._src_pixels.c.o -MF test/pixels.p/.._src_pixels.c.o.d -o test/pixels.p/.._src_pixels.c.o -c src/pixels.c
src/pixels.c:21:10: fatal error: 'libdrm/drm_fourcc.h' file not found
#include <libdrm/drm_fourcc.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by jbeich** [comment]
Note, on FreeBSD cross-compilation is often done via poudriere (as used by official package builders) which already isolates host from target. I don't have/use Linux, so don't understand "host leakage" being fixed by d0cf1595af15.

**Comment by jbeich** [comment]
Generally, `-isystem` is preferred over `-I` when using includes from (system) packages due to the way search paths are ordered and out-of-scope warnings are hidden. I don't know what `-I=` does as it appears missing from GCC manpage and is too short/has special characters for Google/DuckDuckGo.

**Comment by any1** [comment]
The man page entry for `-I` says the following:

> If dir begins with = or $SYSROOT, then the = or $SYSROOT is replaced by the sysroot prefix; see --sysrootand -isysroot.

I can see how it's hard to find because the string `-I=` doesn't appear anywhere in the document.

Could it be that the sysroot of your environment is set to an unexpected value?

**Comment by jbeich** [comment]
> Could it be that the sysroot of your environment is set to an unexpected value?

I don't use sysroot.

```c
$ cat a.c
#include <libdrm/drm_fourcc.h>
int main() {}

$ cc -I=/usr/local/include a.c
a.c:1:10: fatal error: 'libdrm/drm_fourcc.h' file not found
#include <libdrm/drm_fourcc.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

If Meson is run with `CFLAGS+=-v` then during build I see

```
ignoring nonexistent directory "=/usr/local/include"
```

However, during non-tests build something else adds `-I/usr/local/include`, so it builds fine without tests.

**Comment by any1** [comment]
Hmm, I had assumed that if gcc wasn't built with sysroot, the = would be replaced with an empty string. That's probably not the case. If you set `--sysroot=/`, does that do anything?

**Comment by jbeich** [comment]
> If you set `--sysroot=/`, does that do anything?

Makes `-I=/usr/local/include` actually work.

**Comment by jbeich** [comment]
If you need to get libdrm flags from pkg-config without overriding search order try using `include_type: system` like https://github.com/emersion/libliftoff/commit/009570230398.

**Comment by any1** [comment]
I think this might be the solution: https://mesonbuild.com/Reference-manual_returned_dep.html#deppartial_dependency

**Comment by any1** [comment]
I pushed a `partial_dependency` based patch to master. Does that solve the problem?

**Comment by jbeich** [comment]
> Does that solve the problem?

No due to missing `libdrm_inc` in test/meson.build

**Comment by any1** [comment]
Ahh, that was a bit hasty of me. Fixed now.

**Comment by jbeich** [comment]
Builds fine now, so [packaged](https://github.com/freebsd/freebsd-ports/commit/6161b3cd353a).

**Comment by any1** [comment]
Thanks!
