### PR TITLE
Unbreak build on BSDs

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by f20ffb5e1efe. `IPPROTO_TCP` requires `<netinet/in.h>` while `TCP_NODELAY` requires `<netinet/tcp.h>`, both on Linux (glibc, musl) and on BSDs (DragonFly, FreeBSD, NetBSD, OpenBSD). Likely missed due to header bootlegging. To investigate on Linux (where it builds fine "as is") inject `#error` into `<netinet/in.h>` to let compiler show intermediate headers.

See also https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html

```c
$ meson setup /tmp/neatvnc_build
$ meson compile -C /tmp/neatvnc_build
[...]
src/server.c:1119:17: error: use of undeclared identifier 'IPPROTO_TCP'
        setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
                       ^
```

### CODE REVIEW

**Comment by any1** [comment]
Thanks!
